name: Auto Deploy

on:
  workflow_run:
    workflows:
      - "Auto Update"
    types:
      - "completed"
  workflow_dispatch:

jobs:
  Tailscale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Cleanup
        run: python cleanup.py
        env:
          TS_API_DOMAIN: ${{ secrets.TS_API_DOMAIN }}
          TS_TAG: ${{ secrets.TS_TAG }}
          TS_API_TOKEN: ${{ secrets.TS_API_TOKEN }}
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Deploy
        run: flyctl deploy --remote-only