name: Auto Update

on:
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:

jobs:
  Tailscale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update Tailscale version
        run: |
          current_version=$(head -n1 Dockerfile | sed -e "s/^ARG TSVERSION=//")
          latest_version=$(curl https://pkgs.tailscale.com/stable/ | grep tailscale_ -m 1 | cut -d'_' -f 2)
          if [ "$current_version" != "$latest_version" ]; then
            sed -i "1 s/.*/ARG TSVERSION=$latest_version/" Dockerfile
          fi
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Dockerfile
          git commit -m "GitHub Action: Tailscale version update"
          git push